---
title: "Perturbation Analysis"
author: "Intekhab Hossain"
date: "1/26/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE, cache= T}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, 
                      warning = FALSE, fig_width = 15,
                      fig.height = 15)
```

```{r, results=F}
liblist = c('parallel', 'doSNOW', 'stringr','MASS',
            "nleqslv", "data.table", "deSolve", "ggplot2")
sapply(liblist, library, character.only = TRUE)

setwd("C:/STUDIES/RESEARCH/neural_ODE/ground_truth_simulator/code")
#import simulator code
source('Classes.R')
source('GraphGRN_core.R')
source('GraphGRN.R')
source('SimulationGRN_core_init_var.R')
source('SimulationGRN_init_var.R')

get_edge_params <- function(edgeset){
  X = lapply(edgeset,
             function(edge){
               return(list(from = edge@from,
                           to = edge@to,
                           weight = edge@weight,
                           activation = edge@activation,
                           EC50 = edge@EC50, 
                           n = edge@n))
               
             }
  )
  return(rbindlist(X))
}


load("full_network.RData")

#seed to make multiple simulation reproducible
originseed = 608978

#generate seeds for 1000 simulations
set.seed(originseed)
simseeds = sample.int(1E7, 1000)

#----simulation parameters----
#simulation parameters
nsamp = 10 #number of samples
netSize = 150 #network size of sampled networks
minTFs = 10 #minimum number of TFs enforced on sampled networks
expnoise = 0 #experimental noise standard deviation (normal)
bionoise = 0 #biological noise standard deviation (superimposed log-normal)
propbimodal = 0 #proportion of bimodal genes (may be << prop*netSize)

#use seed number 102 to perform one simulation
#using R3.5 will give the same results as sim102 packages in the dcanr package
# The random number generator was changed in R3.6 therefore different results
# will be generated
simseed = simseeds[102]

#----1: sample network and create simulation----
set.seed(simseed)
#grnSmall = sampleGraph(grnFull, netSize, minTFs, seed = simseed)
grnSmall = sampleGraph(grnFull, netSize, minTFs, seed = simseed)
grnSmall = randomizeParams(grnSmall, 'linear-like', simseed)

simSmall = new(
    'SimulationGRN',
    graph = grnSmall,
    seed = simseed,
    propBimodal = propbimodal,
    expnoise = expnoise,
    bionoise = bionoise
)
  
  #----2: simulate data and generate truth matrix----
  #identify genes with bimodal expression
bimgenes = unlist(lapply(simSmall$inputModels, function(x) length(x$prop)))
bimgenes = names(bimgenes)[bimgenes == 2]
  
  #simulate dataset
time_stamps <- 0:9
```

```{r}
makePerturbationPlots <- function(datamat){
  datamat <- datamat[time %in% c(0,1,2,9),]
  cols_to_transpose <- setdiff(names(datamat),c("sample","time"))
  time_cols <- paste("time",time_stamps,sep = "_")
  datamat <- melt(datamat, id.vars = c("sample","time"),
                  measure.vars = cols_to_transpose)
  samp_1_datamat <- datamat[sample ==1,]
  samp_1_datamat[,sample:= NULL]
  setnames(samp_1_datamat, old = "value", new = "samp_1_value")
  plot_data <- merge(datamat, samp_1_datamat, 
                     by = c("time","variable"))
  setnames(plot_data, 
           old = c("variable","value","samp_1_value"),
           new = c("node","expression","sample_1_expression"))
  
  plot_data[, input_node := "Output Node"]
  plot_data[grepl("_input",node), input_node := "Input Node"]
  plot_data[,node := gsub("_input","",node)]
  plot_data[, time:= paste("Time", time, sep = " = ")]
  plot_data[, sample:= paste("Sample", sample, sep = ":")]
  plot_data$time_f = factor(plot_data$time, 
                            levels=c("Time = 0", 
                                     "Time = 1",
                                     "Time = 2",
                                     "Time = 9"))
  
  ggplot(data = plot_data, aes(x = sample_1_expression, 
                               y = expression, 
                               color = input_node)) + 
    geom_abline(intercept = 0, slope = 1, color = "black", lwd = 1)+
    geom_point() +
    theme_bw() + 
    facet_grid(sample~time_f)
  
}
```

# {.tabset .tabset-pills}
## Constant input conditions across samples
```{r}
simu_list = simulateDataset(simSmall, nsamp, 
                            timeStamps = time_stamps, 
                            constantInputGenes  = T,
                            constantOutputGenes = F)
datamat = simu_list$emat
makePerturbationPlots(datamat)
```


## Varying input conditions across samples
```{r}
simu_list = simulateDataset(simSmall, nsamp, 
                            timeStamps = time_stamps, 
                            constantInputGenes  = F,
                            constantOutputGenes = F)
datamat = simu_list$emat
makePerturbationPlots(datamat)
```
